---
# tasks file for s4dfarm

- name: Check if packmate directory exists
  ansible.builtin.stat:
    path: /root/s4dfarm
  register: dir_stat

# Не клонируем заново s4dfarm, если уже есть его дирректория
- name: Create s4dfarm directory
  ansible.builtin.file:
    path: /root/s4dfarm
    state: directory
    mode: '0755'
  when: not dir_stat.stat.exists

- name: Clone s4dfarm repo
  ansible.builtin.git:
    repo: https://github.com/C4T-BuT-S4D/S4DFarm.git
    dest: /root/s4dfarm/
  when: not dir_stat.stat.exists

- name: Pull postgres image
  ansible.builtin.command: docker pull postgres:14.1-alpine --platform amd64

- name: Pull redis image
  ansible.builtin.command: docker pull redis:7.2.0-alpine --platform amd64
  
- name: Replace SERVER_PASSWORD
  ansible.builtin.replace:
    path: /root/s4dfarm/server/app/config.py
    regexp: "'1234'"
    replace: "'{{ universal_pass }}'"

- name: Debug message after installation 
  debug:
    msg: Настройте и запустите  S4DFARM в директории /root/s4dfarm/server/app/config.py

