---
# tasks file for post-install
#
# {{ ansible_eth1.ipv4.address }} заменена на {{ ansible_default_ipv4.address }}

  - name: All ready message 
    debug:
      msg: 
        - "Packmate"
        - "—————————————————"
        - "Address: http://{{ ansible_default_ipv4.address }}:65000"
        - "Creds: BinaryBears : {{ universal_pass }}"
        - "http://BinaryBears:{{ universal_pass }}@{{ ansible_default_ipv4.address }}:65000"
        - ""
        - "Farm"
        - "—————————————————"
        - " Address: http://{{ ansible_default_ipv4.address }}:5137"
        - " Creds: {{ universal_pass }}"
        - " http://{{ ansible_default_ipv4.address }}:5137/?password={{ universal_pass }}"
        - ""
        - "Code-Server"
        - "—————————————————"
        - "Address: http://{{ ansible_default_ipv4.address }}:8080"
        - "Creds: {{ universal_pass }}"
        - ""
        - "Firegex"
        - "—————————————————"
        - "Address: http://{{ ansible_default_ipv4.address }}:4444"
        - "Creds: {{ universal_pass }}"

